### ISSUE TITLE
Bei Ausführung des docker-scripts soll die timezone in der postgresql.conf angepasst werden

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#1]
The timezone stored in **postgresql.conf** should be changed to 'Europe/Berlin', so that the time_stamps, which are passed to the database, are not changed. 

PostgreSQL installed via Windows: timezone = 'CET'.
PostgreSQL via docker-script: timezone = 'Etc/UTC'.
If I set the timezone manually from " timezone = 'Etc/UTC' " to " timezone = 'Etc/UTC' " then the timestamp would fit.

It would definitely be good if we had the option to choose between default and expert installation when starting the "docker-script". The standard user needs the following choices:

- Number of databases/containers.
- Manual selection of ports
- postgres password

It makes no sense if the standard user can influence the size of the logfile.
In the expert installation you can add all functions.
We should talk about this again though.

**Comment by nikoksr** [comment]
Closed by #3.
