### ISSUE TITLE
Funktion 4 TOP Live (J) funktioniert nicht  

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#12]
@nikoksr 
Wenn ich mit dem epc.sh Script v.0.25.3-alpha die Funktion Top aufrufe und mir die aktuellen Live Daten ansehen möchte, wird mir zuerst sämtliche geloggten Daten Rückwirkend vom 06.09. an, angezeigt. Ich habe dann mit dem Script aus dem aktuellen Branch getestet und damit hat die Live TOP Funktion funktioniert und mir wurden direkt nur die Live Daten angezeigt welche ich durch Zugriffe auf die Datenbank erhalten habe. Im Screen per Pfeil markiert der Export von letzter Nacht.

![grafik](https://user-images.githubusercontent.com/48161297/132337435-2f1d6ab9-5156-471d-8f90-d6a8ff4f2bee.png)

**Comment by thomasksr** [comment]
Ein Erneuter Aufruf der Live Funktion brachte auch keine Hilfe

**Comment by nikoksr** [comment]
Fixed in 7b61c25a3f9f65bdf22b744491a5c81072025a3b.
