### ISSUE TITLE
PostgreSQL Version 14 lässt sich nicht von Loco koppeln

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#17]
@nikoksr 
Zur Zeit ist es nicht möglich die Postgresql Version von Loco aus zu koppeln.
Ich habe leider keine weiterführende Fehlermeldung oder sonst welche Infos. Kannst du bitte vorübergehend die 14 Version ausschließen? Wir haben die komplette Anleitung online gestellt und da ich in der nächsten Woche nicht im Büro bin könnte es für meine Kollegen etwas eng werden

**Comment by nikoksr** [comment]
Created dedicated branch [loco](https://github.com/nikoksr/docker-scripts/tree/loco).

Closed in 02287d737ddadb3c214fc7619648c331191b0711.
