### ISSUE TITLE
Container werden nicht mehr über die Auswahl "2) Postgres-Container auflisten" im Menu angezeigt

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#18]
@nikoksr  , einen zuvor mit dem epc.sh Script angelegten Container kann man sich über den Punkt 2 im Menü nicht mehr anzeigen lassen. Auch eine Löschung sämtlicher Container, Images und Volumes brachte keine Verbesserung. Der zuvor erstelle Container lässt sich nur mit docker container ls  anzeigen. Wenn ich aber im Menü den Punkt 3 auswähle werden mir alle Container angezeigt.

Bitte um eine zeitnahe Lösung. Danke

**Comment by nikoksr** [comment]
@thomasksr ist der Issue eigentlich noch relevant? Falls nein, darfst du ihn gerne schließen.

**Comment by thomasksr** [comment]
Der Fehler besteht nicht mehr.

**Comment by thomasksr** [comment]
Ist geschlossen

Niko Köser ***@***.***> schrieb am So., 8. Mai 2022, 01:41:
