### ISSUE TITLE
Rechtschreibfehler Maximal Größer einer Log-Datei

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#2]
Hi @nikoksr, in Zeile 545 vom epc.sh Sript hat sich ein Rechtschreibfehler eingeschlichen.
Bitte Größer in Größe ändern. Siehe Grafik

![grafik](https://user-images.githubusercontent.com/48161297/130361297-72fbe489-38c3-4af5-8dd9-f3faec4df5e2.png)

**Comment by nikoksr** [comment]
cc @thomasksr 

Fixed in #6.
