### ISSUE TITLE
Rechtschreibfehler in der Hilfe

### ISSUE THREAD

**Issue by thomasksr** [nikoksr/docker-scripts#23]
In der Hilfe von epc.sh steht in der Beschreibung für -v --version "Die Versoin des Scripts anzeigen", hier ist das Wort Version falsch geschrieben. Bitte um Änderung.

![image](https://user-images.githubusercontent.com/48161297/190898835-d7dbd1b1-81b2-4ab0-ac15-2e78513eb9f3.png)

**Comment by nikoksr** [comment]
Closed in #24
